version: '3.2'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    image: aijanai/matecat-filters
    ports:
      - 8732:8732

  redis:
    image: redis

  amq:
    image: rmohr/activemq

  mysql:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: matecat
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    # volumes:
    #   - ./conf/mysql.conf:/etc/mysql/conf.d
    
  matecat:
    image: matecat:latest
    depends_on: 
      - mysql
    ## Remove this environment block if you don't need it ##
    ports:
      - 80:80
      - 443:443
      - 7788:7788
    environment:
      #XDEBUG_CONFIG: docker.for.mac.localhost
      FILTERS_ADDRESS: http://filters:8732/
      #FILTERS_ADDRESS: "https://translated-matecat-filters-v1.p.mashape.com"
      #SMTP_HOST: 10.30.1.225
      #SMTP_PORT: 2637
      ENABLE_OUTSOURCE: "false"
    ## Remove this environment block if you don't need it ##
    
    command: ["/run-matecat.sh", "/run-tm-analysis.sh", "/run-fast-analysis.sh"]

  #   volumes:
  #     - ~/matecat_storage:/var/www/matecat/storage
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 7788:7788
  #   networks:
  #      - matecat-network
  #   links:
  #     - mysql
  #     - redis
  #     - amq
  #     - filters

  # matecat-tm-daemon:
  #   image: matecat:latest

  #   command: ["/run-tm-analysis.sh"]

  #   volumes:
  #     - /Users/albertomassidda/matecat_local_storage:/var/www/matecat/local_storage:rw
  #   networks:
  #      - matecat-network
  #   links:
  #     - mysql
  #     - redis
  #     - amq
  #     - filters
  #     - matecat

  # matecat-fast-daemon:
  #   image: matecat:latest

  #   command: ["/run-fast-analysis.sh"]

  #   volumes:
  #     - /Users/albertomassidda/matecat_local_storage:/var/www/matecat/local_storage:rw
  #   networks:
  #      - matecat-network
  #   links:
  #     - mysql
  #     - redis
  #     - amq
  #     - filters
  #     - matecat
